import XCTest
@testable import RealtimeVoice

final class RealtimeSessionUpdateTests: XCTestCase {

    func testSessionUpdateIncludesTools() throws {
        let tool = RealtimeTool(
            name: "hermes_ask",
            description: "Ask the agent",
            parametersJSON: #"{"type":"object","properties":{"question":{"type":"string"}},"required":["question"]}"#
        )
        let client = OpenAIRealtimeClient(apiKey: "test", config: .init(tools: [tool]))
        let session = client.sessionUpdateObject()

        XCTAssertEqual(session["tool_choice"] as? String, "auto")
        let tools = session["tools"] as? [[String: Any]]
        XCTAssertEqual(tools?.count, 1)
        XCTAssertEqual(tools?.first?["type"] as? String, "function")
        XCTAssertEqual(tools?.first?["name"] as? String, "hermes_ask")
        let parameters = tools?.first?["parameters"] as? [String: Any]
        XCTAssertEqual(parameters?["type"] as? String, "object")
    }

    func testSessionUpdateOmitsToolsWhenEmpty() {
        let client = OpenAIRealtimeClient(apiKey: "test", config: .init())
        let session = client.sessionUpdateObject()
        XCTAssertNil(session["tools"])
        XCTAssertNil(session["tool_choice"])
    }
}

/// Locks the direct-WebSocket JSON to Gemini's current Live API contract. These
/// messages are not generated by an SDK, so a casing or shape regression makes a
/// voice session connect but never receive microphone audio.
final class GeminiLiveWireFormatTests: XCTestCase {

    func testSetupUsesCurrentCamelCaseFields() throws {
        let tool = RealtimeTool(name: "lookup", description: "Lookup", parametersJSON: #"{"type":"object"}"#)
        let message = GeminiLiveClient.setupMessage(config: .init(
            model: "gemini-3.1-flash-live-preview", voice: "Aoede", instructions: "Be helpful", tools: [tool]
        ))

        let setup = try XCTUnwrap(message["setup"] as? [String: Any])
        XCTAssertEqual(setup["model"] as? String, "models/gemini-3.1-flash-live-preview")
        XCTAssertNotNil(setup["generationConfig"])
        XCTAssertNotNil(setup["systemInstruction"])
        XCTAssertNotNil(setup["inputAudioTranscription"])
        XCTAssertNotNil(setup["outputAudioTranscription"])
        XCTAssertNil(setup["generation_config"])
        let generation = try XCTUnwrap(setup["generationConfig"] as? [String: Any])
        XCTAssertEqual(generation["responseModalities"] as? [String], ["AUDIO"])
        let tools = try XCTUnwrap(setup["tools"] as? [[String: Any]])
        XCTAssertEqual(tools.count, 2)
        XCTAssertNotNil(tools.first?["googleSearch"])
        XCTAssertNotNil(tools.last?["functionDeclarations"])
        let systemInstruction = try XCTUnwrap(setup["systemInstruction"] as? [String: Any])
        let parts = try XCTUnwrap(systemInstruction["parts"] as? [[String: String]])
        XCTAssertTrue(parts.first?["text"]?.contains("Google Search") == true)
    }

    func testRealtimeMessagesUseDedicatedAudioVideoAndTextFields() throws {
        let audio = GeminiLiveClient.audioMessage(Data([0x01, 0x02]))
        let audioBody = try XCTUnwrap(audio["realtimeInput"] as? [String: Any])
        let audioData = try XCTUnwrap(audioBody["audio"] as? [String: Any])
        XCTAssertEqual(audioData["mimeType"] as? String, "audio/pcm;rate=16000")
        XCTAssertEqual(audioData["data"] as? String, "AQI=")
        XCTAssertNil(audioBody["mediaChunks"])

        let image = GeminiLiveClient.imageMessage(Data([0xFF]))
        let imageBody = try XCTUnwrap(image["realtimeInput"] as? [String: Any])
        let videoData = try XCTUnwrap(imageBody["video"] as? [String: Any])
        XCTAssertEqual(videoData["mimeType"] as? String, "image/jpeg")

        let text = GeminiLiveClient.textMessage("Hello")
        XCTAssertEqual((text["realtimeInput"] as? [String: Any])?["text"] as? String, "Hello")
    }

    func testToolResponsesUseCurrentCamelCaseFields() throws {
        let message = GeminiLiveClient.toolResponseMessage(callID: "call-1", response: ["ok": true])
        let response = try XCTUnwrap(message["toolResponse"] as? [String: Any])
        let calls = try XCTUnwrap(response["functionResponses"] as? [[String: Any]])
        XCTAssertEqual(calls.first?["id"] as? String, "call-1")
        XCTAssertEqual((calls.first?["response"] as? [String: Any])?["ok"] as? Bool, true)
    }
}

/// Live test: opens the OpenAI Realtime WebSocket and confirms the session
/// handshake (auth + protocol). Skipped unless OPENAI_API_KEY is set.
final class RealtimeHandshakeTests: XCTestCase {

    func testRealtimeSessionHandshake() async throws {
        guard let key = ProcessInfo.processInfo.environment["OPENAI_API_KEY"], !key.isEmpty else {
            throw XCTSkip("OPENAI_API_KEY not set — skipping live realtime handshake test")
        }
        let client = OpenAIRealtimeClient(apiKey: key, config: .init(audio: true))
        client.connect()
        defer { client.disconnect() }

        // Wait up to 15s for session.created (or an error).
        let deadline = Date().addingTimeInterval(15)
        var sawSessionCreated = false
        for await event in client.events {
            switch event {
            case .sessionCreated, .sessionUpdated:
                sawSessionCreated = true
            case let .error(message):
                XCTFail("Realtime error: \(message)")
                return
            default:
                break
            }
            if sawSessionCreated || Date() > deadline { break }
        }
        XCTAssertTrue(sawSessionCreated, "Did not receive session.created within timeout")
    }

    /// Live test: validates the raw Gemini Live WebSocket setup used by the app.
    /// It is skipped locally unless GEMINI_API_KEY is supplied to the test process.
    func testGeminiLiveSessionHandshake() async throws {
        guard let key = ProcessInfo.processInfo.environment["GEMINI_API_KEY"], !key.isEmpty else {
            throw XCTSkip("GEMINI_API_KEY not set — skipping Gemini Live handshake test")
        }
        let client = GeminiLiveClient(
            apiKey: key,
            config: .init(model: "gemini-3.1-flash-live-preview", instructions: "Reply briefly.", audio: true)
        )
        defer { client.disconnect() }

        let connected = expectation(description: "Gemini setup complete")
        let receivedResponse = expectation(description: "Gemini returned audio or transcript")
        let task = Task {
            for await event in client.events {
                switch event {
                case .sessionCreated:
                    connected.fulfill()
                    client.sendText("Say ready.")
                case let .assistantAudioDelta(data):
                    if !data.isEmpty { receivedResponse.fulfill(); return }
                case let .assistantTextDelta(text):
                    if !text.isEmpty { receivedResponse.fulfill(); return }
                case let .error(message):
                    XCTFail("Gemini Live error: \(message)")
                    return
                default:
                    break
                }
            }
        }
        defer { task.cancel() }

        client.connect()
        await fulfillment(of: [connected, receivedResponse], timeout: 25)
    }
}
